name: blinknews
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"             # Background color of the splash screen
  image: assets/splash.png     # Your splash image (ensure this exists)
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/
  #   - assets/splash.png        # Declare your splash image here

  # Example for custom fonts (optional, remove if not using fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
